### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by nkasenides** [Xristos3/fitness_forge#29]
When adding an event, the user should be able to select the time of the event. In addition, events are not particularly useful right now as there are no reminders, and they are not linked to any particular workout or another activity.

**Comment by Xristos3** [comment]
I don't know how to implement the time and as you wrote this feature as it is, is not useful right now and I am seriously thinking about removing it because I think it will not have a big significance in my application and I want your opinion on that regard.

**Comment by nkasenides** [comment]
Ok , please keep these as they are.
