### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by nkasenides** [Xristos3/fitness_forge#31]
In the password reset, it's enough to only ask the user about their email, as they will need to type a new password in the email form they receive. So they do not have to enter a new password in the app too.

**Comment by Xristos3** [comment]
but that's how the password is saved in firestore for the current user i don't know any other way to have the new password saved to firestore in order to perform the login

**Comment by nkasenides** [comment]
> but that's how the password is saved in firestore for the current user i don't know any other way to have the new password saved to firestore in order to perform the login

Actually, the new password is not needed in the app. Look in forgotpassword_screen.dart, in line 76. You only need the email of the user to send the password reset email. In the next line, you are updating the password in the user's profile (in the real-time database).

For authentication in general, avoid manually checking usernames and passwords. Instead, what you can do is to use the authentication system provided by Firebase: 

https://firebase.google.com/docs/auth/flutter/password-auth#sign_in_a_user_with_an_email_address_and_password

The password does not need to be stored in the database, it can be verified through the authentication mechanism as shown above, which also eliminates the need to have the password entered in the app during the forgot password process.

This mechanism can also help you with the 'Remember me' process, as when authenticating a user, Firebase will automatically remember that they are signed in. You can save the credentials of the signed in user in shared preferences, and use that to remember whether the user has already signed in.

For example, this code checks whether you have signed in, and you can adjust to allow the app to redirect the user to the home page instead of asking them to log in.

if (FirebaseAuth.instance.currentUser != null) {
  print(FirebaseAuth.instance.currentUser?.uid);
}

This requires a log in through the authentication mechanism linked above.
